ImageData=[
    {
        id:1,
        imageLink:"images/pexels-jill-wellington-40192.jpg",
        category:"sunrise",
    },
    {
        id:2,
        imageLink:"images/pexels-no-name-66997.jpg",
        category:"sunrise",
    },
    {
        id:3,
        imageLink:"images/pexels-sebastian-arie-voortman-189349.jpg",
        category:"sunrise",
    },
    {
        id:4,
        imageLink:"images/sunset1.jpg",
        category:"sunset",
    },
    {
        id:5,
        imageLink:"images/sunset2.jpg",
        category:"sunset",
    },
    {
        id:6,
        imageLink:"images/sunset3.jpg",
        category:"sunset",
    },
    {
        id:7,
        imageLink:"images/flower1.jpg",
        category:"flower",
    },
    {
        id:8,
        imageLink:"images/flower2.jpg",
        category:"flower",
    },
    {
        id:9,
        imageLink:"images/flower3.jpg",
        category:"flower",
    },
    {
        id:10,
        imageLink:"images/nature1.jpg",
        category:"nature",
    },
    {
        id:11,
        imageLink:"images/nature2.jpg",
        category:"nature",
    },
    {
        id:12,
        imageLink:"images/nature3.jpg",
        category:"nature",
    },

]
export default ImageData;